const SITE_CONFIG = {
  siteName: "APP GARAGE",
  contactEmail: "maruw@outlook.jp",
  contactSubject: "アプリ・ホームページ制作についての相談",
  contactBodyItems: [
    "お名前：",
    "会社名・店舗名：",
    "現在困っていること：",
    "作りたいアプリ・ホームページの内容：",
    "希望する機能・ページ内容：",
    "利用予定の端末：",
    "利用予定人数：",
    "ご予算：",
    "保守プランの希望：",
    "その他：",
  ],
};

const TYPE_FILTERS = [
  { id: "all", label: "すべて" },
  { id: "free", label: "無料アプリ" },
  { id: "development", label: "開発中" },
  { id: "case-study", label: "開発事例" },
];

const CATEGORY_FILTERS = [
  { id: "all", label: "すべてのカテゴリ" },
  { id: "アンケート作成", label: "アンケート作成" },
  { id: "業務連絡", label: "業務連絡" },
  { id: "店舗管理", label: "店舗管理" },
  { id: "売上管理", label: "売上管理" },
  { id: "集計ツール", label: "集計ツール" },
  { id: "介護施設向け", label: "介護施設向け" },
  { id: "画像生成支援", label: "画像生成支援" },
  { id: "ゲーム", label: "ゲーム" },
  { id: "社内ポータル", label: "社内ポータル" },
  { id: "チェックリスト", label: "チェックリスト" },
  { id: "報告書作成", label: "報告書作成" },
];

const APPS = [
  {
    id: "sugukiku",
    title: "すぐ聞く",
    catchCopy: "スマホで1分、アンケート作成。",
    category: "アンケート・業務効率化",
    description:
      "スマートフォンから、短時間で簡単にアンケートを作成できるWebアプリです。難しい設定を減らし、誰でも迷わず使えることを目指しています。",
    longDescription:
      "アンケートの作成、共有、回答、集計をスマートフォン中心で進められる無料Webアプリです。現場で使いやすいよう、入力項目や画面遷移をシンプルにしています。",
    features: [
      "スマートフォンから作成可能",
      "約1分でアンケートを作成",
      "シンプルで分かりやすい操作",
      "回答結果を見やすく確認",
      "アプリのインストール不要",
      "無料で利用可能",
    ],
    usage: [
      "アプリを開きます。",
      "アンケート名と質問を入力します。",
      "作成された回答URLを共有します。",
      "集まった回答結果を確認します。",
    ],
    targetUsers: "店舗、施設、個人事業主、アンケートをすぐ作りたい人",
    devices: "スマートフォン / パソコン",
    status: "公開中",
    type: "free",
    icon: "聞",
    accentColor: "#6dff9f",
    tags: ["アンケート作成", "業務効率化", "スマホ対応", "集計ツール"],
    url: "https://sugukiku.maruw501.workers.dev/",
    image: "",
    featured: true,
    published: true,
    label: "第1弾無料アプリ",
  },
  {
    id: "free-app-02",
    title: "フォトレポ",
    catchCopy: "撮る、書く、まとめる。現場報告を簡単に。スマホひとつで。",
    category: "報告書作成",
    description:
      "写真付きの点検・巡回レポートをスマホで簡単作成。インストール不要ですぐに使えます。",
    longDescription:
      "写真を撮って、コメントを入力するだけ。現場の状況をPDF・Excelにまとめて、すぐに共有できます。面倒な報告書づくりを、もっと速く、もっと簡単に。",
    features: [
      "写真報告をスマートフォンで作成",
      "写真とコメントをまとめて資料化",
      "PDF・Excel形式で共有",
      "点検・巡回レポートに対応",
      "アプリのインストール不要",
      "無料で利用可能",
    ],
    usage: [
      "アプリを開きます。",
      "写真を追加し、必要なコメントを入力します。",
      "内容を確認します。",
      "PDF・Excel形式で出力して共有します。",
    ],
    targetUsers: "点検、巡回、現場報告、写真付きレポートを作成する人",
    devices: "スマートフォン / パソコン",
    status: "公開中",
    type: "free",
    icon: "写",
    accentColor: "#6dff9f",
    tags: ["写真報告", "現場報告", "報告書作成", "PDF", "Excel", "スマホ対応"],
    url: "https://script.google.com/macros/s/AKfycbyVl2fDZCn8bQ6rFEU5_YWEgX1egxb9c9Ogj0cnIz_eOuPEslR9jNHlchN8SQZ0NMDH/exec",
    image: "",
    featured: true,
    published: true,
    label: "おすすめ",
  },
  {
    id: "free-app-03",
    title: "第3弾アプリ",
    catchCopy: "",
    category: "無料公開予定",
    description: "現在、新しい無料アプリを開発しています。",
    longDescription: "詳細準備中",
    features: [],
    targetUsers: "詳細準備中",
    devices: "スマートフォン / パソコン",
    status: "開発中",
    progress: "企画中",
    type: "development",
    icon: "03",
    accentColor: "#ffbd66",
    tags: ["無料公開予定"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "lunch-board",
    title: "昼食連絡ボード",
    catchCopy: "介護施設と食事提供側の確認をひとつに。",
    category: "介護施設向け",
    description:
      "介護施設の昼食数を、施設側と提供側で確認するための共有アプリです。",
    longDescription:
      "利用者ごとの食事形態、欠席、注意事項、日別・月別の食数確認などを扱える業務向けアプリです。現在は一般公開用ではなく、開発事例として掲載しています。",
    features: ["日別の昼食数確認", "食事形態の管理", "月合計の確認", "施設側・提供側の確認フロー"],
    targetUsers: "介護施設、食事提供事業者、施設スタッフ",
    devices: "スマートフォン / タブレット / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "昼",
    accentColor: "#b992ff",
    tags: ["介護施設向け", "業務連絡", "集計ツール"],
    url: "",
    image: "",
    featured: true,
    published: true,
  },
  {
    id: "sales-message-maker",
    title: "営業連絡メーカー",
    catchCopy: "",
    category: "業務連絡",
    description:
      "予定、天気、イベント情報を整理し、毎日の営業連絡文を効率よく作成する業務支援アプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "店舗運営、営業担当者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "営",
    accentColor: "#b992ff",
    tags: ["業務連絡", "店舗管理", "文章作成"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "visibility-check",
    title: "見通しチェック",
    catchCopy: "",
    category: "チェックリスト",
    description:
      "道路や駐車場などの見通しを確認し、危険箇所の把握をサポートする便利ツール。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "安全確認を行う担当者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "見",
    accentColor: "#b992ff",
    tags: ["チェックリスト", "安全確認", "便利ツール"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "am-portal",
    title: "AMポータル",
    catchCopy: "",
    category: "社内ポータル",
    description:
      "売上、実績、週報など、複数の業務情報を一か所にまとめて管理するポータルアプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "管理者、店舗・事業部の担当者",
    devices: "パソコン / タブレット",
    status: "開発事例",
    type: "case-study",
    icon: "AM",
    accentColor: "#b992ff",
    tags: ["社内ポータル", "売上管理", "データ管理"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "prompt-studio",
    title: "画像プロンプト工房",
    catchCopy: "",
    category: "画像生成支援",
    description:
      "イラスト生成に使う文章を、目的やテイストに合わせて簡単に組み立てられるアプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "画像生成を使う制作者、企画担当者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "画",
    accentColor: "#b992ff",
    tags: ["画像生成支援", "プロンプト", "クリエイティブ"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "presidents-ambition",
    title: "社長の野望",
    catchCopy: "",
    category: "ゲーム",
    description:
      "会社経営と企業買収をテーマにした、オリジナル経営シミュレーションゲーム。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "ゲーム利用者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "社",
    accentColor: "#b992ff",
    tags: ["ゲーム", "経営ゲーム", "シミュレーション"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
];

window.SITE_CONFIG = SITE_CONFIG;
window.TYPE_FILTERS = TYPE_FILTERS;
window.CATEGORY_FILTERS = CATEGORY_FILTERS;
window.APPS = APPS;
