const SITE_CONFIG = {
  siteName: "APP GARAGE",
  contactEmail: "maruw@outlook.jp",
  contactSubject: "アプリ・ホームページ制作についての相談",
  contactBodyItems: [
    "お名前：",
    "会社名・店舗名：",
    "現在困っていること：",
    "作りたいアプリ・ホームページの内容：",
    "希望する機能・ページ内容：",
    "利用予定の端末：",
    "利用予定人数：",
    "ご予算：",
    "保守プランの希望：",
    "その他：",
  ],
};

const APPS = [
  {
    id: "sugukiku",
    title: "すぐ聞く",
    catchCopy: "スマホで1分、アンケート作成。",
    category: "アンケート・業務効率化",
    description:
      "スマートフォンから、短時間で簡単にアンケートを作成できるWebアプリです。難しい設定を減らし、誰でも迷わず使えることを目指しています。",
    longDescription:
      "アンケートの作成、共有、回答、集計をスマートフォン中心で進められる無料Webアプリです。現場で使いやすいよう、入力項目や画面遷移をシンプルにしています。",
    features: [
      "スマートフォンから作成可能",
      "約1分でアンケートを作成",
      "URL・QRコードで回答を共有",
      "回答結果の自動集計・CSV出力",
      "作成者のみログイン・回答者は不要",
      "アプリのインストール不要",
      "無料で利用可能",
    ],
    usage: [
      "紹介ページからアプリを開き、作成者として登録・ログインします。",
      "テンプレートを選ぶか、新規作成からアンケート名と質問を入力します。",
      "作成された回答URLまたはQRコードを共有します。",
      "管理画面で集まった回答結果を確認します。",
    ],
    targetUsers: "店舗、施設、個人事業主、アンケートをすぐ作りたい人",
    devices: "スマートフォン / パソコン",
    status: "公開中",
    type: "free",
    icon: "聞",
    accentColor: "#6dff9f",
    tags: ["アンケート作成", "業務効率化", "スマホ対応", "集計ツール"],
    url: "https://app-garage.pages.dev/sugukiku/",
    image: "",
    featured: true,
    published: true,
    label: "第1弾無料アプリ",
  },
  {
    id: "free-app-02",
    title: "フォトレポ",
    catchCopy: "撮る、書く、まとめる。現場報告を簡単に。スマホひとつで。",
    category: "報告書作成",
    description:
      "写真付きの点検・巡回レポートをスマホで簡単作成。インストール不要ですぐに使えます。",
    longDescription:
      "写真を撮って、コメントを入力するだけ。現場の状況をPDF・Excelにまとめて、すぐに共有できます。面倒な報告書づくりを、もっと速く、もっと簡単に。",
    features: [
      "写真報告をスマートフォンで作成",
      "写真とコメントをまとめて資料化",
      "PDF・Excel形式で共有",
      "点検・巡回レポートに対応",
      "アプリのインストール不要",
      "無料で利用可能",
    ],
    usage: [
      "アプリを開きます。",
      "写真を追加し、必要なコメントを入力します。",
      "内容を確認します。",
      "PDF・Excel形式で出力して共有します。",
    ],
    targetUsers: "点検、巡回、現場報告、写真付きレポートを作成する人",
    devices: "スマートフォン / パソコン",
    status: "公開中",
    type: "free",
    icon: "写",
    accentColor: "#6dff9f",
    tags: ["写真報告", "現場報告", "報告書作成", "PDF", "Excel", "スマホ対応"],
    url: "https://app-garage.pages.dev/photorepo/",
    image: "",
    featured: true,
    published: true,
    label: "おすすめ",
  },
  {
    id: "kantan-link",
    title: "かんたんリンク",
    catchCopy: "よく使うWebページを、大きなボタンからすぐ開く。",
    category: "PCツール",
    description:
      "よく使うWebページを、大きく見やすいボタンから開けるWindows用の無料ショートカットアプリです。",
    longDescription:
      "かんたんリンクは、毎日使うWebページを登録して、PCからすぐ開ける無料アプリです。4列×4行で最大16個のショートカットを表示でき、登録タブやよく使うショートカット機能で、仕事や日常のPC操作をスムーズにします。",
    features: [
      "1画面に最大16個のショートカットを表示",
      "名前を変更できる5つの登録タブ",
      "よく使うショートカットを自動表示",
      "URLの登録・削除に対応",
      "登録データは利用中のPC内だけに保存",
      "広告・アプリ内課金・利用者情報の収集なし",
    ],
    usage: [
      "紹介ページからWindows版インストーラーをダウンロードします。",
      "インストーラーを実行し、画面の案内に沿ってインストールします。",
      "よく使うWebページの名前とURLを登録します。",
      "大きなボタンから、必要なページをすぐ開けます。",
    ],
    targetUsers: "よく使うWebページをPCでまとめて開きたい人、事務作業、店舗・施設スタッフ",
    devices: "Windows 10 / Windows 11（64ビット版）",
    status: "公開中",
    type: "free",
    icon: "PC",
    accentColor: "#6dff9f",
    tags: ["PCツール", "ショートカット", "Windows", "リンク管理", "業務効率化"],
    url: "https://app-garage.pages.dev/kantanlink/",
    image: "",
    featured: true,
    published: true,
    label: "第3弾無料アプリ",
  },
  {
    id: "lunch-board",
    title: "昼食連絡ボード",
    catchCopy: "介護施設と食事提供側の確認をひとつに。",
    category: "介護施設向け",
    description:
      "介護施設の昼食数を、施設側と提供側で確認するための共有アプリです。",
    longDescription:
      "利用者ごとの食事形態、欠席、注意事項、日別・月別の食数確認などを扱える業務向けアプリです。現在は一般公開用ではなく、開発事例として掲載しています。",
    features: ["日別の昼食数確認", "食事形態の管理", "月合計の確認", "施設側・提供側の確認フロー"],
    targetUsers: "介護施設、食事提供事業者、施設スタッフ",
    devices: "スマートフォン / タブレット / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "昼",
    accentColor: "#b992ff",
    tags: ["介護施設向け", "業務連絡", "集計ツール"],
    url: "",
    image: "",
    featured: true,
    published: true,
  },
  {
    id: "sales-message-maker",
    title: "営業連絡メーカー",
    catchCopy: "",
    category: "業務連絡",
    description:
      "予定、天気、イベント情報を整理し、毎日の営業連絡文を効率よく作成する業務支援アプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "店舗運営、営業担当者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "営",
    accentColor: "#b992ff",
    tags: ["業務連絡", "店舗管理", "文章作成"],
    url: "",
    image: "",
    featured: false,
    published: false,
  },
  {
    id: "clinic-reservation-system",
    title: "クリニック予約管理システム",
    catchCopy: "予約、キャンセル、受付状況をひとつに。",
    category: "予約管理",
    description:
      "クリニックの診療予約、予約枠、キャンセル、受付状況を見やすく管理する業務向けシステム。",
    longDescription:
      "電話、紙、LINEなどに分かれがちな予約管理を、クリニックの運用に合わせて整理する予約管理システムです。受付スタッフ、担当者、管理者が予約状況を確認しやすい画面を作成できます。",
    features: ["診療予約の管理", "予約枠の管理", "キャンセル状況の確認", "受付状況の見える化"],
    targetUsers: "クリニック、医院、受付スタッフ、予約管理を効率化したい事業者",
    devices: "スマートフォン / タブレット / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "予",
    accentColor: "#b992ff",
    tags: ["予約管理", "クリニック", "受付管理", "業務効率化"],
    url: "",
    image: "",
    featured: false,
    published: true,
  },
  {
    id: "am-portal",
    title: "AMポータル",
    catchCopy: "",
    category: "社内ポータル",
    description:
      "売上、実績、週報など、複数の業務情報を一か所にまとめて管理するポータルアプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "管理者、店舗・事業部の担当者",
    devices: "パソコン / タブレット",
    status: "開発事例",
    type: "case-study",
    icon: "AM",
    accentColor: "#b992ff",
    tags: ["社内ポータル", "売上管理", "データ管理"],
    url: "",
    image: "",
    featured: false,
    published: false,
  },
  {
    id: "prompt-studio",
    title: "画像プロンプト工房",
    catchCopy: "",
    category: "画像生成支援",
    description:
      "イラスト生成に使う文章を、目的やテイストに合わせて簡単に組み立てられるアプリ。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "画像生成を使う制作者、企画担当者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "画",
    accentColor: "#b992ff",
    tags: ["画像生成支援", "プロンプト", "クリエイティブ"],
    url: "",
    image: "",
    featured: false,
    published: false,
  },
  {
    id: "presidents-ambition",
    title: "社長の野望",
    catchCopy: "",
    category: "ゲーム",
    description:
      "会社経営と企業買収をテーマにした、オリジナル経営シミュレーションゲーム。",
    longDescription: "詳細準備中",
    features: ["詳細準備中"],
    targetUsers: "ゲーム利用者",
    devices: "スマートフォン / パソコン",
    status: "開発事例",
    type: "case-study",
    icon: "社",
    accentColor: "#b992ff",
    tags: ["ゲーム", "経営ゲーム", "シミュレーション"],
    url: "",
    image: "",
    featured: false,
    published: false,
  },
];

window.SITE_CONFIG = SITE_CONFIG;
window.APPS = APPS;
